{% set version = "0.4-3" %}

package:
  name: r-snow
  version: {{ version|replace("-", "_") }}

source:
  fn: snow_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/snow_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/snow/snow_{{ version }}.tar.gz

  sha256: 8512537daf334ea2b8074dbb80cf5e959a403a78d68bc1e97664e8a4f64576d8

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('snow')"  # [not win]
    - "\"%R%\" -e \"library('snow')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/snow/index.html
  license: GPL-2
  summary: Support for simple parallel computing in R.

extra:
  recipe-maintainers:
    - tomnl
    - johanneskoester
    - bgruening
