{% set version = "0.4-4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-snow
  version: {{ version|replace("-", "_") }}

source:
  fn: snow_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/snow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/snow/snow_{{ version }}.tar.gz
  sha256: 84587f46f222a96f3e2fde10ad6ec6ddbd878f4e917cd926d632f61a87db13c9

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('snow')"           # [not win]
    - "\"%R%\" -e \"library('snow')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=snow
  license: GPL
  summary: Support for simple parallel computing in R.
  license_family: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - tomnl
