appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: EO8Rd0I8XcjLXT8IRGFcW7hD0eKqK8elkjv2Xc1VtXUmc2X5ZMtxQ7yNIXCECQVUOMXf9cqhD5rfZ+uz91CRcpeUtMStinScT5yI79nWv/eoeaOK6wgrmpxnwcr/VXvur7DuPCpaU4W2R9LcqKVzjnGNJRxAIouWDXPMLOgLvQ9WyPPevt4kiT5iSYjCe3OdHtuommX6Rvnlyg5Jb20K8FPYAenmVKJYEDFWms2ZYbKio+BYMblVNridsffnWs4ACk38v+860UOP3bRoC4ZjYZzv92S8A32SePbDMBhCGlNAEwnzKNEfiCwcEWTfLKc5FR7phWWo75hFuxXoRLkeZgIOWUsJBm2tlUX17W4lb/HLOje8EIMAu80oijUCZuWGuZRmXnJ37i+HQ56B+8xGpmL3KG7dhLJz7kyIEb0BxO8DluIS6NWR/HCA8hbw3wcinwYmyCtb1aifhZVOGdu1t7ITN70SlXdk3Zv1sE6LyD36x62j8YivTZMm0UFuPeqykfwEFaiIU2GkZD5O4sHgPB8d2+pR+hziP1yKN8sWMjQcJL0yRbJvOKxco1TgHLRkuC8ofATLJF5tBTTDspOdXM98Zq90MKNCJA0dY9THstYZHix4f6TMDvTMRAGS1YXMUuNlRzurY98R79YzTbXJ76QBbTjZ49PurBI6mCuR30U=}
bot:
  automerge: true
